name: inception

networks:
  mynetwork:

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - /home/fcasaubo/data/site:/var/www/html
    networks:
      - mynetwork
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - ./www:/var/www/html
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - mynetwork
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - 3306
    networks:
      - mynetwork
    volumes:
      - /home/fcasaubo/data/database:/var/lib/mysql
  