CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER wpuser@'%' IDENTIFIED BY 'password';
CREATE USER wpadmin@'%' IDENTIFIED BY 'adminpassword';
GRANT ALL PRIVILEGES ON *.* TO 'wpadmin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;